# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

homepage_url: /
global_header_text: DWP

# Site settings
title: Example Serivce Header
description: 'information on description'
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site

govuk_template_assets: /assets

header_class: with-proposition

# Build settings
markdown: kramdown

exclude:
    - node_modules
